#!/bin/bash
# To be run from within a daemontools instance.
# Edit DBDIR and MOVEUSER appropriately.
DBDIR=./db
MOVEUSER=

cd $DBDIR

NOW=$(date '+%Y%m%d%H%M%S')
PRELAUNCH=prelaunch/$NOW
NEWEST=$(ls move.checkpoint.* | sort -nr | head -1)

mkdir -p $PRELAUNCH
cp core db db.old move.checkpoint.* $PRELAUNCH

if [ -n "$NEWEST" ]; then
    mv db db.old
    mv $NEWEST db
    rm -f move.checkpoint.*
fi

CMD="exec ./move db restart.move"
if [ -n "$MOVEUSER" ]; then
    exec su $MOVEUSER -c "ulimit -c unlimited; $CMD"
else
    ulimit -c unlimited
    $CMD
fi
