#!/bin/bash
# To be run from within a daemontools instance.
# Edit DBDIR and MOVEUSER appropriately.
DBDIR=./db
MOVEUSER=

cd $DBDIR

CMD="exec ../tricks/checkpoint-cleanup move.checkpoint. 300 6"
if [ -n "$MOVEUSER" ]; then
    exec su $MOVEUSER -c "$CMD"
else
    $CMD
fi
